/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_fmindexbuilder_free: (a: number, b: number) => void;
export const __wbg_fmindexhandle_free: (a: number, b: number) => void;
export const fmindexbuilder_add_fasta: (a: number, b: number, c: number) => [number, number];
export const fmindexbuilder_add_sequence: (a: number, b: number, c: number) => [number, number];
export const fmindexbuilder_build_cpu: (a: number) => [number, number, number];
export const fmindexbuilder_build_gpu: (a: number) => any;
export const fmindexbuilder_clear: (a: number) => void;
export const fmindexbuilder_new: (a: number) => number;
export const fmindexbuilder_sequence_count: (a: number) => number;
export const fmindexhandle_count: (a: number, b: number, c: number) => [number, number, number];
export const fmindexhandle_from_bytes: (a: number, b: number) => [number, number, number];
export const fmindexhandle_locate: (a: number, b: number, c: number) => [number, number, number, number];
export const fmindexhandle_num_sequences: (a: number) => number;
export const fmindexhandle_text_len: (a: number) => number;
export const fmindexhandle_to_bytes: (a: number) => [number, number, number, number];
export const wasm_bindgen__convert__closures_____invoke__h465b7f6cc7174e01: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen__convert__closures_____invoke__h23411f3a1b5b82b2: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen__convert__closures_____invoke__h0360c65602824ded: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
